-- One-time backfill. 008 fixed a real gap: a session's length/flow was decided before any call's
-- latency existed, so there was no genuine correlation between a slow /api/time-off/balance/:id
-- call and whether the session continued afterward — confirmed against 30 real days of data that
-- the drop-off signal had never fired, not because of a UI bug, but because nothing correlated
-- existed to find. 008's seed_one_day_of_meridian_data is now fixed going forward (applied live),
-- but the ~90 days of session_traces already in the table were generated by the OLD, uncorrelated
-- logic (either 004's original one-time run, or earlier cron days before this fix) — without
-- regenerating them, a real signal would be diluted by mostly-old, uncorrelated history for weeks.
--
-- session_traces is the only table that needs an explicit wipe first: 004's session_ids
-- (`emp-<day_offset>-<i>`) don't match the day-tag pattern (`emp-<YYYYMMDD>-<i>`) that
-- seed_one_day_of_meridian_data's own DELETE looks for, so simply re-looping the function over
-- history would insert new, corrected rows *alongside* the old ones instead of replacing them.
-- endpoint_stats/endpoint_daily_rollups/violations don't have this problem (they're deleted by
-- window_start / upserted by day / deleted by created_at range, all of which are consistent
-- regardless of which script produced them) — re-running the function for historical dates
-- naturally refreshes them too, which is harmless collateral churn (same distributions, new
-- random values), not a real change in any of their conclusions.
--
-- Also a genuine improvement beyond the drop-off fix: seed_one_day_of_meridian_data uses real
-- calendar-date-driven weekday/review-cycle/open-enrollment/holiday-lull/new-hire-wave logic,
-- while 004's original run only had simple day-offset weekend detection — this backfill makes the
-- entire historical window consistently calendar-aware, not a mix of old-simple and new-aware data.

DO $$
DECLARE
  team uuid := '017d549d-0278-4227-a91d-a74fbf6bb15d';
  d date;
BEGIN
  DELETE FROM session_traces WHERE team_id = team;

  FOR d IN SELECT generate_series(CURRENT_DATE - 89, CURRENT_DATE, '1 day')::date LOOP
    PERFORM seed_one_day_of_meridian_data(d);
  END LOOP;
END $$;
